### PR TITLE
Fix spec fields

### PR DESCRIPTION
**Pull request by saniazara01**

### CODE REVIEW

**Review by stefanfrehse — COMMENTED** [review]
LGTM. Do we enforce somewhere that this is a breaking change? I couldn't find it.

**Comment by saniazara01** [comment]
> LGTM. Do we enforce somewhere that this is a breaking change? I couldn't find it.

I'm sorry, I don't get what you mean by enforce.

**Comment by stefanfrehse** [comment]
Is the API version changed that indicates a breaking change?

**Comment by saniazara01** [comment]
> Is the API version changed that indicates a breaking change?

Ah. I thought we had a chat about it but I'm sorry for not being very clear. We're making these changes in the current version and hence I'll patch the existing resources.

**Comment by stefanfrehse** [comment]
Ok. It is clear now.

**Review by stefanfrehse — APPROVED** [review]

**Pull request merged**
